# Generated by Django 6.0.3 on 2026-03-21 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('respiracao', 'Respiração'), ('mindfulness', 'Mindfulness'), ('relaxamento', 'Relaxamento Muscular'), ('sentidos', '5 Sentidos'), ('reflexao', 'Reflexão do Dia')], max_length=50)),
                ('descricao', models.TextField()),
                ('audio', models.FileField(blank=True, null=True, upload_to='audios/')),
            ],
        ),
        migrations.CreateModel(
            name='FraseMotivacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('data_disponibilizacao', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='perfil',
            name='tipo',
            field=models.CharField(choices=[('livre', 'Utilizador Livre'), ('paciente', 'Paciente'), ('psicologo', 'Psicólogo')], default='livre', max_length=20),
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(choices=[('semanal', 'Semanal'), ('mensal', 'Mensal')], default='semanal', max_length=20)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('estatisticas', models.JSONField(default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios', to=settings.AUTH_USER_MODEL)),
                ('psicologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios_gerados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='RelacaoPsicologoPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_associacao', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('paciente', models.ForeignKey(limit_choices_to={'perfil__tipo': 'paciente'}, on_delete=django.db.models.deletion.CASCADE, related_name='psicologos', to=settings.AUTH_USER_MODEL)),
                ('psicologo', models.ForeignKey(limit_choices_to={'perfil__tipo': 'psicologo'}, on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('psicologo', 'paciente')},
            },
        ),
    ]
