# Generated by Django 6.0.3 on 2026-03-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_reflexaodia'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='data_nasc',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
